---
driver:
  name: vagrant
  communicator: winrm

transport:
  name: winrm

verifier:
  name: pester

provisioner:
  name: dsc

platforms:
- name: Windows2012R2
  driver:
    box: Windows2012R2

suites:
  - name: AddDSCLogging